#server:
#  port: 8060
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#logging:
#  level:
#    root: debug
#  pattern: 
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
#              
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#      - id: banquet
#        uri: lb://banquet
#        predicates:
#        - Path=/banquet/**
#        filters:
#        - RewritePath=/banquet/(?<path>.*), /$\{path}
#      - id: authenticator
#        uri: lb://authenticator
#        predicates:
#        - Path=/auth/**
#        #filters:
#        #- RewritePath=/bebe/(?<path>.*), /$\{path}
#      - id: department-service
#        uri: lb://department-service
#        predicates:
#        - Path=/department/**
#        filters:
#        - RewritePath=/department/(?<path>.*), /$\{path}